#!/usr/bin/env bash
domain=$1
subdomain=$2

check_subdomain() {
    result=$(dig $1.$domain | awk '/ANSWER SECTION/ {getline; print $4}')
    echo "The subdomain $1 is a A record and points to $result"
}

if [ -z "$subdomain" ]; then
    check_subdomain www
    check_subdomain lb-01
    check_subdomain web-01
    check_subdomain web-02
else
    check_subdomain $subdomain
fi
