#!/usr/bin/env bash
# Configure your domain zone so that the subdomain 
# www points to your load-balancer IP (lb-01)
param () {
    REC=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $REC" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  param "$1" "www"
  param "$1" "lb-01"
  param "$1" "web-01"
  param "$1" "web-02"
elif [ "$#" == 2 ]
then
  param "$1" "$2"
fi
