#!/bin/bash

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Get the current server's hostname
current_hostname=$(hostname)

# Add custom header configuration to Nginx
sudo bash -c 'cat <<EOF > /etc/nginx/conf.d/custom_headers.conf
server_tokens off;
add_header X-Served-By $current_hostname;
EOF'

# Restart Nginx to apply changes
sudo systemctl restart nginx
